"""update_database_schema

Revision ID: 8611a77fc751
Revises: d1e2f3g4h5i6
Create Date: 2026-05-31 01:40:03.986724

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8611a77fc751'
down_revision: Union[str, None] = 'd1e2f3g4h5i6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('venues_name_key'), 'venues', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('venues_name_key'), 'venues', ['name'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
